name = "isbn-notify"
main = "src/index.ts"
compatibility_date = "2024-06-05"

[triggers]
crons = ["0 2,6,10 * * 1-5"] # Runs Monday-Friday at 09:00, 13:00, 17:00 WIB (02:00, 06:00, 10:00 UTC)

[[d1_databases]]
binding = "DB"
database_name = "isbn-db"
database_id = "local-isbn-db" # Placehoder for remote deploy, will be used locally by default
